services:
  langgraph-chatbot:
    container_name: langgraph_middleware
    build: .
    ports:
      - "10000:8000"
    environment:
      - OLLAMA_BASE_URL=http://192.168.86.45:11434
      - OLLAMA_MODEL=qwen2.5:7b
    restart: unless-stopped
    shm_size: '2gb'  # Shared memory for browser
    security_opt:
      - seccomp:unconfined  # Allows browser sandboxing
     
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open_webui
    restart: unless-stopped
    ports:
      - "7860:8080"
    environment:
      OLLAMA_API_URL: "http://192.168.86.45:11434"
      LOG_LEVEL: "debug"
    volumes:
      - /home/tom/open-webui:/app/backend/data